#!/bin/bash

set -e

shopt -s expand_aliases

alias bosh='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/bosh/Gemfile bundle exec bosh'

usage_and_exit() {
  cat <<EOF
BOSH Control starts or stops all your BOSH deployments.

Usage: boshctl <command>
Examples:
  boshctl start
  boshctl stop
EOF
  exit 1
}

is_logged_in() {
  ! $(bosh status | grep -q 'not logged in')
}

get_cf_deployment() {
  bosh deployments 2>/dev/null | grep -o '^| cf-.*' | cut -d \| -f 2 | tr -d ' '
}

get_product_deployments() {
  bosh deployments 2>/dev/null | grep -o '^| p-.*\|^| apm-.*' | cut -d \| -f 2 | tr -d ' '
}

stop() {
  local deployment=$1
  local deployment_file="/var/tempest/workspaces/default/deployments/$deployment.yml"
  bosh deployment $deployment_file
  bosh -n -N stop --hard
}

start() {
  local deployment=$1
  local deployment_file="/var/tempest/workspaces/default/deployments/$deployment.yml"
  bosh deployment $deployment_file
  bosh -n -N start
}

# Stop all other products then CF
stop_all() {
  if ! is_logged_in; then
    bosh login
  fi
  for deployment in $(get_product_deployments); do
    stop $deployment
  done
  stop $(get_cf_deployment)
}

# Start CF then all other products
start_all() {
  if ! is_logged_in; then
    bosh login
  fi
  start $(get_cf_deployment)
  for deployment in $(get_product_deployments); do
    start $deployment
  done
}

CMD=$1 ARG=$2

if [ "start" = "$CMD" ]; then
  start_all
  bosh tasks
elif [ "stop" = "$CMD" ]; then
  stop_all
  bosh tasks
else
  usage_and_exit
fi
