#!/bin/bash

set -eu
set -o pipefail

if ! command -v uaac >/dev/null 2>&1; then
  shopt -s expand_aliases
  alias uaac='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/uaac/Gemfile bundle exec uaac'
fi

OPSMAN_HOST=${OPSMAN_HOST:-localhost}

usage_and_exit() {
  cat <<EOF
Usage: opsman <command> [options]
Examples:
  opsman login
  opsman upload cf-1.8.5-build.4.pivotal
  opsman upload bosh-stemcell-3363.24-vsphere-esxi-ubuntu-trusty-go_agent.tgz
EOF
  exit 1
}

error_and_exit() {
  echo "$1" && exit 1
}

login_to_uaac() {
  local OPSMAN_USER=
  read -r -p "Ops Manager User: " OPSMAN_USER

  local OPSMAN_PASS=
  read -r -s -p "Ops Manager Pass: " OPSMAN_PASS

  uaac target https://$OPSMAN_HOST/uaa --skip-ssl-validation

  uaac token owner get opsman "$OPSMAN_USER" -p "$OPSMAN_PASS" -s ''

  printf 'User \e[33m%s\e[0m logged in successfully.\n' "$OPSMAN_USER"
}

is_valid_access_token() {
  local UAA_ACCESS_TOKEN=${1:?UAA_ACCESS_TOKEN null or not set}
  [ -n "$UAA_ACCESS_TOKEN" ] || return 1

  local STATUS_CODE=$(curl https://$OPSMAN_HOST/uaa/check_token -k -L -G \
    -s -o /dev/null -w "%{http_code}" \
    -u "opsman:" \
    -d token_type=bearer \
    -d token="$UAA_ACCESS_TOKEN")

    [ "200" = "$STATUS_CODE" ]
}

get_uaac_access_token() {
  local UAA_ACCESS_TOKEN=$(uaac context | grep access_token | awk '{ print $2 }')
  if ! is_valid_access_token "$UAA_ACCESS_TOKEN"; then
    login_to_uaac
    UAA_ACCESS_TOKEN=$(uaac context | grep access_token | awk '{ print $2 }')
  fi
  echo "$UAA_ACCESS_TOKEN"
}

is_stemcell() {
  local filename=${1:?filename null or not set}
  [[ "$filename" == *stemcell*.tgz ]]
}

upload_file() {
  local LOCAL_FILE_NAME=${1:-}
  if [ -z "$LOCAL_FILE_NAME" ]; then
    read -r -p "Local file name: " LOCAL_FILE_NAME
  fi

  if [ ! -f "$LOCAL_FILE_NAME" ]; then
    error_and_exit "Invalid file: $LOCAL_FILE_NAME"
  fi

  local UAA_ACCESS_TOKEN=$(get_uaac_access_token)

  if is_stemcell "$LOCAL_FILE_NAME"; then
    printf 'Uploading stemcell: \e[33m%s\e[0m\n' "$LOCAL_FILE_NAME"

    curl "https://$OPSMAN_HOST/api/v0/stemcells" \
      -k -# -o /dev/null \
      -X POST \
      -H "Authorization: Bearer $UAA_ACCESS_TOKEN" \
      -F "stemcell[file]=@$LOCAL_FILE_NAME"
  else
    printf 'Uploading tile: \e[33m%s\e[0m\n' "$LOCAL_FILE_NAME"

    curl "https://$OPSMAN_HOST/api/v0/available_products" \
      -k -# -o /dev/null \
      -X POST \
      -H "Authorization: Bearer $UAA_ACCESS_TOKEN" \
      -F "product[file]=@$LOCAL_FILE_NAME"
  fi
}

upload_files() {
  for filename in $1; do
    upload_file "$filename"
  done
}

CMD=$1 ARG=$2

if [ "login" = "$CMD" ]; then
  login_to_uaac
elif [ "upload" = "$CMD" ]; then
  upload_files "$ARG"
else
  usage_and_exit
fi
